pgdata:
  image: busybox:latest
  volumes:
    - /var/lib/postgresql/data

postgres:
  image: postgres:9.5
  ports:
    - "2345:5432"
  environment:
    POSTGRES_PASSWORD: email
    POSTGRES_USER: email
    POSTGRES_DATABASE: email
  volumes_from:
    - pgdata
  volumes:
    - .:/data
